version: '3'

services:
  ib-docker:
    build:
      context: ./
    image: rcludw/ib-docker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 120s

    ports:
      - "4003:4003"
      - "5900:5900"
    volumes:
      - ./IBController.ini:/root/IBController/IBController.ini
      - ./jts.ini:/root/Jts/jts.ini
    environment:
      - TZ=Australia/Adelaide
      # Variables pulled from /IBController/IBControllerGatewayStart.sh
      - VNC_PASSWORD=password
      - TWS_MAJOR_VRSN=963
      - IBC_INI=/root/IBController/IBController.ini
      - TRADING_MODE=
      - IBC_PATH=/opt/IBController
      - TWS_PATH=/root/Jts/ibgateway
      - TWS_CONFIG_PATH=/root/Jts
      - LOG_PATH=/opt/IBController/Logs
      - TWSUSERID=edemo
      - TWSPASSWORD=demouser
      - FIXUSERID=
      - FIXPASSWORD=
      - JAVA_PATH=
      - APP=GATEWAY
